### PR TITLE
Update layout to make inlay on homepage responsive

### PR DESCRIPTION
**Pull request by kasprzyk-sz**
So we can:

image

### CODE REVIEW

**Comment by sturobson** [comment]
I'm guessing that these changes are not effecting the group pages that use `vf-wp` before we merge things in and get releases going? 

Also - what are you changing here that didn't work before? 

Is it specific to the news site or is it something related to `vf-core` that needs addressing rather than, potentially, creating some developer debt on a repo making use of it?

Also - can we make use of issues so that we can holistically track what the problems are, for future development as much as the present, and how they can be resoled. The steps we should take are

1. There's a problem, file an issue.
2. Discuss as much as possible and define a solution.
3. Work on solution in a branch and submit a PR
4. Test
5. Merge if all is good.

**Comment by khawkins98** [comment]
There's an issue with vf-inlay across the board at the medium responsive point. The sidebar goes from ~300px on "desktop" to ~800px on "tablet"

Looks like:

https://wwwdev.ebi.ac.uk/about/teams/training/about/

image

https://visual-framework.github.io/vf-core/components/detail/vf-inlay.html

image

Don't necessarily need this approach in vf-core but we do need a tablet approach/breakpoint.

**Comment by khawkins98** [comment]
Just realised we're on the vf-wp project. 

This one's more of a hot-fix for vf-wp, more holitistic fix would be needed over at https://github.com/visual-framework/vf-core/pull/750

**Comment by sturobson** [comment]
seeing how the 'did you know' box responds - it's more an issue with the components rather than the layout?

**Comment by sturobson** [comment]
> a hot-fix 

alarm bells are ringing. 

If is for `vf-wp` or for the news site.

**Comment by khawkins98** [comment]
News is part of the vf-wp project so it gets the same issues that problem with the sidebar as the group sites.

**Pull request merged**
