### PR TITLE
Feature/vf wp news child theme

### PR DESCRIPTION
**Pull request by khawkins98**
I'm helping @kasprzyk-sz investigate options for making a VF 2.0 version of the EMBL News site.

It would provide a lot of benefits if the "vf-wp-news" theme were a child theme of `vf-wp`.

I know I'm jumping ahead of some of your work @dbushell , but I could use your guidance on the best way to supersede some vf-wp logic.

For example, rather than unsetting some classes from `vf-wp` on the `<body>` tag, I'd rather replace the function; this is how I've managed to:

in `wp-content/themes/vf-wp/functions/theme.php`  add an `if function_exists`:

```php 
/**
 * Append <body> class for Visual Framework
 */
if (!function_exists('vf__body_class')) {
  add_filter('body_class', 'vf__body_class');

  function vf__body_class($classes) {
    $classes[] = 'vf-body';
    $classes[] = 'vf-wp-theme';
    if (is_singular('vf_block') || is_singular('vf_container')) {
      return $classes;
    }
    $classes[] = 'vf-u-background-color-ui--grey';
    return $classes;
  }
}
```

And then in `wp-content/themes/vf-wp-news/functions/theme.php` I can:

```php
add_filter('body_class', 'vf__body_class');

function vf__body_class($classes) {
  // $classes[] = 'vf-body';
  $classes[] = 'vf-wp-theme';
  if (is_singular('vf_block') || is_singular('vf_container')) {
    return $classes;
  }
  // $classes[] = 'vf-u-background-color-ui--grey';
  return $classes;
}
```

See commit 5dfa0ae

Is this the right approach?

### CODE REVIEW

**Comment by sturobson** [comment]
rather than `vf-wp-news` isn't this better as a 'themed' thing? If I'm reading it right with adding the background colour. 

Surely a 'general' child-theme with various colour theme options is more long-term than having 'domain specific' variants?

**Comment by sturobson** [comment]
of course, I could be jumping the gun on this issue anyhow :D

**Comment by khawkins98** [comment]
I _suspect_ the news theme might be a little bit of its own weird beast / design patterns. I'd actually think that it probably shouldn't live here ... so that one day it can go off and die once we make a proper news site theme ... or news is fully integrated into EMBL.org via the contentHub.

**Comment by dbushell** [comment]
Hey Ken,

What I'd like to do very soon is move `vf-wp-groups` to a child theme too.

So that `vf-wp-groups` and `vf-wp-news` share a parent theme that is less opinionated to avoid this issue and probably quite limited just with useful common functions.

However, for this example the better solution is to add a priority number to your filter:

```php
add_filter('body_class', 'my_custom_body_class', 99, 1);
```

The first number `99` is the order WordPress calls the filters. Because the default is `10` the `vf-wp` filter will run before yours. The second number `1` is the expected parameters (just `$classes` in this case).

With `99` (or anything higher than `10`) your filter runs last. You can amend the `$classes` array and remove anything you don't want, or just return a new array.

If you're really want to control the filter use `PHP_INT_MAX` and you can have the final say.

**Comment by dbushell** [comment]
It's possible to use WordPress actions and filters to define our own in the parent theme and plugins. So any 'optionated' logic like this should in be overwritable. I'll need to review everything I've done and make sure those new filters are documented!

**Comment by khawkins98** [comment]
All the above makes sense. Thanks for the tips.

I think what will probably make the most sense is for:

1. Any near-term needs for EMBL News to be done is some other repo
2. Await the refactor of `vf-wp` parent theme and `vf-wp-groups` theme 
3. Once that's done to refactor the News theme following the lead of of `vf-wp-groups`

@kasprzyk-sz: I think it still makes sense to try and make the initial `vf-wp-news` by making a rough child theme of `vf-wp` as it will make bringing the news site "into the fold" a lot easier in the future (we'll already have compatibility with the contentHub, taxonomy, etc.). If we don't use `vf-wp` as a base we'll have to make all that from scratch.

**Comment by khawkins98** [comment]
Now eclipsed by @kasprzyk-sz 's vf-wp-news child theme.

**Pull request closed without merging**
