### PR TITLE
adds vf-intro block

### PR DESCRIPTION
**Pull request by kasprzyk-sz**

### CODE REVIEW

**Comment by sturobson** [comment]
should the `vf-banner` code snippet be in here too? Or am I misreading the file?

**Comment by kasprzyk-sz** [comment]
It appears only on the admin side.

Screenshot 2020-05-18 at 15 29 55

**Comment by sturobson** [comment]
> It appears only on the admin side.

as some sort of 'live demo'?

**Comment by dbushell** [comment]
> > It appears only on the admin side.
> 
> as some sort of 'live demo'?

it's just a placeholder if no content has been entered
otherwise the template is either empty or looks funny

**Comment by dbushell** [comment]
Blocked by #309 

Once that PR is merged I'll make the necessary compatibility updates here.

**Pull request merged**
