### PR TITLE
fixed vf-grid render loop issue

### PR DESCRIPTION
**Pull request by nitinja**
reference: https://github.com/visual-framework/vf-wp/pull/862

Fixes render loop by moving state-updating functions inside an effect with dependencies.

### CODE REVIEW

**Comment by khawkins98** [comment]
Szymon, could you check if vf-grid now works correctly in WP 5.7? 

I'd need to reconfigure my dev environment from another project (long story) and would lose quite a bit of time.

**Comment by khawkins98** [comment]
If we can verify this works, we'll need to replicate the work done here and in #862 for embl-grid, vf-tabs and any other react-based blocks.

**Comment by kasprzyk-sz** [comment]
There is no error anymore but the columns in the editor are displayed vertically:

Screenshot 2021-06-30 at 13 48 45

**Comment by khawkins98** [comment]
Hrm, to be sure that's using this branch?

**Comment by khawkins98** [comment]
Oh, you probably need to run `gulp vf-gutenberg`

**Comment by khawkins98** [comment]
I've rebuilt vf-blocks.js and pushed to this branch.

**Comment by kasprzyk-sz** [comment]
Ok, now it's displayed correctly. Just two things: There is a button to add a new block within the grid (below columns)

Screenshot 2021-06-30 at 15 00 54


The column span just removes a column:

Screenshot 2021-06-30 at 15 01 31

**Comment by nitinja** [comment]
Can anyone please explain if the current behavior is ok/not ok? how it used to behave earlier?

**Comment by khawkins98** [comment]
Previously the code looked like:

`         <InnerBlocks allowedBlocks={['vf/grid-column']} templateLock='all' />`

https://github.com/visual-framework/vf-wp/pull/862/files#diff-8a17f1e8ee60b7ef6f4bb7e3823dc3bfa8a5473419cd4899273ebcc162913a32L195

I removed the `allowedBlocks={['vf/grid-column']} templateLock='all'` in my testing of #862 as it seemed to be further breaking things. You might try reading it.

**Comment by nitinja** [comment]
@kasprzyk-sz can you try this with my latest fix? 
Note that, to activate each column, we have to double click it. The issue is currently can not be fixed.

**Comment by nitinja** [comment]
@kasprzyk-sz can you try one more time now?

**Comment by sandykadam** [comment]
Closing this as its fixed in https://github.com/visual-framework/vf-wp/pull/956

**Pull request closed without merging**
