### PR TITLE
vf-gutenberg rollup tasks

### LINKED ISSUE #54: Remove Webpack dependency - use Rollup or just Gulp/Babel
With `vf-core` using **Rollup** and further integration in the works here https://github.com/visual-framework/vf-wp/pull/48 – it would make sense to use Rollup in `vf-wp` too to reduce the size of Node dependencies.

Alternatively, a custom Gulp task (or `gulp-babel`) would likely suffice.

Webpack was only used as a quick solution.

### PR DESCRIPTION
**Pull request by dbushell**
Resolves #54 

todo:

- [x] browser test Gutenberg dev/prod scripts
- [x] test full assets build task

### CODE REVIEW

**Comment by dbushell** [comment]
Hi @khawkins98 do you know why the GitHub automated builds are failing?

Works locally. Don't think I removed any related dependencies.

**Comment by khawkins98** [comment]
Looks like it wants `gulp-better-rollup` to be added to the package.json

https://github.com/visual-framework/vf-wp/pull/578/checks?check_run_id=1378531776#step:4:40

Are the build failures specific to this PR, or all of them?

**Comment by khawkins98** [comment]
Looks like the associated yarn.lock is outdated, I've run it and it's added `gulp-better-rollup`. Committing the updated lockfile.

**Comment by khawkins98** [comment]
Hrm, still didn't work. Going to try pinning the dependencies.

**Comment by khawkins98** [comment]
Seems happy now.

**Comment by dbushell** [comment]
Cheers – looks like I was using NPM and not Yarn.

**Pull request merged**
