### PR TITLE
vf-cluster Gutenberg block

### PR DESCRIPTION
**Pull request by dbushell**
Work in progress

https://github.com/visual-framework/vf-wp/issues/566

### CODE REVIEW

**Comment by dbushell** [comment]
The settings:

Screenshot 2020-11-03 at 10 24 50

**Comment by dbushell** [comment]
Works similar to the VF Grid block adding inner blocks:

Screenshot 2020-11-03 at 10 27 26

The editor layout can sometimes be a little different than the final page because of the additional block inserter.

**Comment by dbushell** [comment]
@kasprzyk-sz this is ready for a test drive if you've time to checkout the `issue/566` branch

**Comment by sturobson** [comment]
is there chance to add some documentation/notes?

As `vf-cluster` is only really beneficial for when you want to lay out content of various width.

**Comment by dbushell** [comment]
> is there chance to add some documentation/notes?
> 
> As `vf-cluster` is only really beneficial for when you want to lay out content of various width.

We probably do need some standard way to link to documentation. Perhaps in the description instead of just "Visual framework (core)" (if Gutenberg allows links there...)

Maybe too to categorise more advanced blocks away from the common ones.

**Pull request merged**
