### PR TITLE
feature/container-templates

### PR DESCRIPTION
**Pull request by dbushell**
Allow container blocks in Gutenberg with "full-width" toggle.

### CODE REVIEW

**Comment by dbushell** [comment]
Fixes #293

**Comment by dbushell** [comment]
Fixes #98

**Comment by dbushell** [comment]
Resolves #142 

This at least provides the necessary framework/workflow for child themes. That mega-issue it a bit too broad in scope!

**Comment by khawkins98** [comment]
Looking forward to using this.

**Pull request merged**
